version: 2.1

defaults: &defaults
  docker:
    - image: cimg/node:22.18.0-browsers
  working_directory: ~/app

jobs:
  install:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: "."
          paths:
            - "package.json"
            - "package-lock.json"
            - "tsconfig.json"
            - "eslint.config.js"
            - "jest.config.cjs"
            - "jest.setup.js"
            - "vite.config.ts"
            - "netlify.toml"
            - "node_modules"
            - ".git/*"
            - ".circleci/*"
            - "src"

  format:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Format
          command: npm run format && npm run tsc

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: "."
          paths:
            - "dist"

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Test
          command: npm run test -- --coverage --coverageReporters=text-summary

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Deploy
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=dist --no-build

workflows:
  version: 2

  branch-workflow:
    jobs:
      - install
      - format:
          requires:
            - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - build
            - format
            - test
          filters:
            branches:
              only: main
